[build]
  base    = "docs"
  publish = "/build"
  command = "sphinx-build source build/docs/"

[[redirects]]
  from = "/docs/*"
  to  = "/docs/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to  = "https://0koara0.github.io/webDesign/:splat"
  status = 200
  force = true